# Generated by Django 3.1.3 on 2020-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
    ]
