# Generated by Django 3.1.3 on 2020-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201202_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
