# Generated by Django 3.1.3 on 2020-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201202_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_sizes',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
