# Generated by Django 3.1.3 on 2020-12-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201202_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_sizes',
        ),
    ]
