# Generated by Django 3.1.3 on 2020-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
