# Generated by Django 3.1.3 on 2020-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201215_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
