# Generated by Django 3.1.3 on 2020-12-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_item_on_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='on_stock',
            new_name='stock',
        ),
    ]
