# Generated by Django 3.1.3 on 2021-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210124_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='country',
            field=models.CharField(default='Bulgaria', max_length=100),
            preserve_default=False,
        ),
    ]
