# Generated by Django 3.1.3 on 2021-01-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_paymentmodel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='country',
        ),
    ]
