# Generated by Django 3.1.3 on 2021-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_paymentmodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='order_info',
            field=models.ManyToManyField(to='shop.Order'),
        ),
    ]
