# Generated by Django 3.1.3 on 2021-01-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_paymentmodel_order_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='order_info',
        ),
    ]
