# Generated by Django 3.1.3 on 2021-02-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Order confirmed', 'Order confirmed!'), ('Order processed', 'Order processed!'), ('Order en route', 'Order dispatched'), ('Order arrived', 'Order arrived!')], max_length=70, null=True),
        ),
    ]
